# -*- mode: ruby -*-
# vi: set ft=ruby :

# This Vagrantfile clones from a base Ubuntu 20.04 Box
# Then runs the commands to install Docker Engine
# Please alter the networking as needed

Vagrant.configure("2") do |config|

  # Use Joe's Box for  ARM64 (Apple Silicon M1/Pro/Extreme) machines using VMware Fusion
  # YOU MUST USE THE VMware Provider to use this Box
  # Run the following command:

  # vagrant plugin install vagrant-vmware-desktop
  config.vm.box = "axnetlabs/axnetlabs_focal_arm64"

  # Use this box if the Hashicorp created box is desired.
  #config.vm.box = "hashicorp/focal64"

  # Configure Port Forwarding as needed.  
  # If access to the container from outside the VM is desired, 
  # Specialize networking will be required, such as public networking or port forwarding
   
  # Expose port 5000 from the VM to the Host. Flask uses tcp 5000 by default
  #config.vm.network "forwarded_port", guest: 5000, host: 5000
  # Or expose a container on the common http port:
  #config.vm.network "forwarded_port", guest: 80, host: 80

  # Specify a host only network if you want.
  # config.vm.network "private_network", ip: "192.168.56.10"

  # Bridge the VM is you want
  # config.vm.network "public_network"

  # Alter VM's setting to increase RAM if needed
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #

  # Use the Vagrant provisioner to install Docker in the VM
  # sudo not needed as the provisioner runs as root
  config.vm.provision "shell", inline: <<-SHELL

  apt-get update

    #should already be installed, but double check
    apt-get install -y ca-certificates curl gnupg lsb-release

    #add Docker package repo to the server
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

    #after Docker repo added to apt, update it.
    apt-get update

    #docker stuff
    apt-get install -y docker-ce docker-ce-cli containerd.io

    # login to VM double check this.  May need to run manually...
    usermod -aG docker vagrant

    #Uncomment to have this ran as part to install (to verify Docker works)
    #or run it manually
    #docker run hello-world
  SHELL
end
